[workspace]
resolver = "2"

members = [ "day*", "no-std-day*", "benchmarks"]

[workspace.lints.rust]
dead_code = "allow"
unused_results = "warn"
unused-crate-dependencies = "allow"

[workspace.dependencies]
divan = "0.1.3"
