[package]
name = "no-std-day01"
version = "0.1.0"
authors = ["Tanguy Soubry"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.10.2", default-features = false }


[lints]
workspace = true
