[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = { workspace = true }
day01 = { path = "../day01" }
no-std-day01 = { path = "../no-std-day01" }

[[bench]]
name = "day01"
path = "benches/day01.rs"
harness = false
